Repository iobda/folk_alchemy, pull requests merged in 2024-08, with the labels that each got.

#19 Add files via upload
  Camazotz.png
  Catsith.png
  Cerberus.png
  clue.png
  help.png
  redcap.png
  siren.png
Labels: art assets

#21 Create pull_request_template.cmd
  .github/pull_request_template.cmd
Labels: enhancement

#22 Дифференциация иконок+анимация
  assets/folklore/Camazotz.png.import
  assets/folklore/Catsith.png.import
  assets/folklore/Cerberus.png.import
  debug_instruments/debug_emergable_label.gd
  resources/shaders/select_element.gdshader
  scenes/element.gd
  scenes/element.tscn
  scenes/guidebook.gd
  scenes/guidebook.tscn
  scenes/main_scene/folklore_counter.gd
  scenes/main_scene/game.tscn
  scenes/main_scene/game_state.gd
  scenes/tip_element.gd
  scenes/tip_element.tscn
  scenes/tip_window.tscn
  scenes/tips.gd
Labels: enhancement

#25 Add files via upload
  Обложка.png
  иконка.png
Labels: art assets

#27 Add files via upload
  effect.png
  fujin.png
  pearl.png
Labels: art assets

#28 фикс багов
  export_presets.cfg
  merge_element.tscn
  resources/shaders/black_text_to_white.gdshader
  resources/shaders/blur.gdshader
  scenes/category.gd
  scenes/element.gd
  scenes/main_scene/folklore_counter.gd
  scenes/main_scene/game.tscn
  scenes/main_scene/game_state.gd
  scenes/merge_element.gd
  scenes/merger.gd
  scenes/merger.tscn
  scenes/pop_folklore.tscn
  scripts/autoload/db_elements.gd
Labels: bug

#29 нарратив iteration2
  effect.png.import
  fujin.png.import
  pearl.png.import
  resources/shaders/black_text_to_white.gdshader
  scenes/guidebook_folklore.tscn
  scenes/how_to_play.tscn
  scenes/main_scene/how_to_play_button.gd
  scenes/pop_folklore.tscn
  scripts/autoload/db_elements.gd
Labels: bug, enhancement

#33 Add files via upload
  ad.png
  clue_not.png
Labels: art assets

#35 Add files via upload
  basilisk.png
  dogsith.png
  lo.png
  vampir.png
  werewolf.png
Labels: art assets

#34 Сжатый шаблон для експорта в веб + исправления в тексте
  export/export_presets/export_presets.cfg
  export_presets.cfg
  scripts/autoload/db_elements.gd
Labels: enhancement

#36 Add files via upload
  fre.png
  koy.png
Labels: art assets

#38 Add files via upload
  dragon.png
  kanashibari.png
  kitsune.png
Labels: art assets

#41 Концовка
  assets/background-book/end.png
  assets/background-book/end.png.import
  scenes/end_screen.gd
  scenes/end_screen.tscn
  scenes/main_scene/game.tscn
  scenes/main_scene/guidebook_button.gd
  scenes/merger.gd
  scenes/pop_folklore.gd
  scripts/autoload/db_elements.gd
Labels: bug, enhancement

#42 ending fix
  scenes/end_screen.gd
  scenes/end_screen.tscn
Labels: bug
